### ISSUE TITLE
Modularity in wasm

### ISSUE THREAD

**Issue by mpizenberg** [sebcrozet/kiss3d#183]
Hi, I'm familiar with the wasm-bindgen and wasm-pack workflow where you can build an exposed module (`lib.rs`) with public methods. I find it quite nice to be able to instantiate your wasm module and call your methods as you wish with fine grained control.

It seems to me that with kiss3d structure and reliance on stdweb, one can only do a main with a window controlling the whole web page. Is there some way of having more control on the web page and render loop? Or is it out of scope for kiss3d?

**Comment by sebcrozet** [comment]
Hi! Kiss3d relies heavily on stdweb for WASM support and I believe it would be quite difficult to make it compatible with wasm-bindgen too (but I have little experience with wasm-bindgen so I may be wrong).

So there is currently no plan to support wasm-bindgen anytime soon, though if anyone manage to make it work, a PR is welcome.

With the current stdweb integration, there is no way to have more control on the render loop itself which is based on [request_animation_frame](https://github.com/sebcrozet/kiss3d/blob/master/src/window/webgl_canvas.rs#L160). Though you are free to execute any code you need at each frame by implementing the `step` method of the [State trait](https://docs.rs/kiss3d/0.21.0/kiss3d/window/trait.State.html#tymethod.step).

Regarding the web page itself, you have full control over it since you already have to provide a [web page](https://github.com/sebcrozet/kiss3d/blob/master/examples/wasm/static/index.html#L18) including a `<canvas>`. Besides this mandatory `<canvas>`, you are free to add anything you need to this web page.

**Comment by mpizenberg** [comment]
Oh, I had not noticed the `static/` dir with an `index.html` file. Thanks, this answer what I needed.

**Comment by codec-abc** [comment]
Hey,

Sorry to bump this. I would be interested to use kiss3D in a project of mine using `wasm-bindgen` since it seems the way forward.  Since the last message is one year old, I would like to know if the situation has changed or if you have a finer idea of what would need to be changed to make it work with `wasm-bindgen`? I might give it a shot but if you have any advice before I dive in I will gladly take them.

**Comment by codec-abc** [comment]
I just give this a try there is definitively some rough edges to convert the project to `wasm-bindgen` only, at least for someone with my experience. The major paint points would be:

- An update of `webgl_bindings.rs`. It depends a lot on the `js!` macro which don't exist with wasm-bindgen. Also it recreates some Js types where `wasm-bindgen` already provide type definition for thanks to the automatic type definition of MDN.
- An change of how array are used. Stdweb's `TypedArray` and `UnsafeTypedArray` are heavily used and would need to be changed. I am not sure what `wasm-bindgen` provides here.
- The update of the event listeners. It doesn't seems to map nicely to what `wasm-bindgen` provides so it needs to be updated also.

I think that's mostly it. The code would probably need a few changes elsewhere but it would probably be really once those 3 points are done.
