### ISSUE TITLE
Mouse grabbing

### ISSUE THREAD

**Issue by jendrikw** [sebcrozet/kiss3d#191]
I'm missing an option to grab the mouse cursor, as seen in FPS or minecraft. Glutin supports this via [set_cursor_grab](https://docs.rs/glutin/0.22.0-alpha5/glutin/window/struct.Window.html#method.set_cursor_grab), so it shouldn't be difficult.

Or is there a way to get the glutin window in kiss and I missed it?

**Comment by sebcrozet** [comment]
Hi! There is currently no way of getting the glutin window in Kiss3D because the actual window type is platform-dependent (we don't use glutin for WASM targets right now). However, we could add a `set_cursor_grab` method to the `Kiss3d` window that calls the glutin method when possible, or does nothing if we are targeting WASM (unless there is a way of doing this on browsers, perhaps by calling some JS?).

**Comment by jendrikw** [comment]
That seems like a good option. Would you accept a PR for this?

**Comment by sebcrozet** [comment]
> Would you accept a PR for this?

That would be great, thanks!

**Comment by gufoe** [comment]
I made #198 to support fps games.
