### ISSUE TITLE
Drawing 2D text on the canvas at a point in 3D world coordinates

### ISSUE THREAD

**Issue by alvinhochun** [sebcrozet/kiss3d#204]
I wanted to draw text at a 3D point as an attempt to quickly display some data. I found no existing function to do it directly, so I am trying with this code to transform the point (using origin for testing) from the 3D space to 2D device space and draw the text at the transformed point:

```rust
let window_size = na::Vector2::new(window.size()[0] as f32, window.size()[1] as f32);
let window_coord = first_person.project(&Point3::origin(), &window_size);
window.draw_text(
    &format!("{}, {}", window_coord.x, window_coord.y),
    &window_coord.into(),
    24.0,
    &font,
    &Point3::new(1.0, 1.0, 1.0),
);
```

([Link to code modified from `examples/camera.rs`](https://gist.github.com/alvinhochun/9cd2f19d3b15c7dd611c38e0c65ec969#file-camera-rs-L62))

This however did not achieve the result I wished for: My attempt is wrong in several ways:

1. The coords obtained from `first_person.project` appears to be using the bottom-left corner as the origin, but as I understand it may be the correct behaviour depending on the definition of "2d screen coordinates", so I can't say it's a bug.
2. The text is drawn in the wrong position as in it's drawn like the coordinates are halved. I guess it might be a bug with the `draw_text` method but not really sure.
3. It panicked with "attempt to add with overflow" when the window is minimized. I tried to add conditions to prevent drawing with coords outside of the window bounds but it still panicked when restoring the window.
4. I've had it panicked on [this `unwrap()`](https://github.com/sebcrozet/kiss3d/blob/5bd8e528818b454ee7f0e3860806d12d5747f8de/src/camera/camera.rs#L64) for certain coordinates (\*1) but I couldn't figure out the reason as I'm not good with linear algebra and 3D graphics.
5. The `project` method does not provide the z-depth of the transformed point to be used to skip drawing for points that are either behind or too far from the camera.

<details>
<summary>(Screenshot describing points 1 and 2)</summary>

![Screenshot describing points 1 and 2](https://user-images.githubusercontent.com/2397650/73653744-e94ea080-46c4-11ea-91e3-f01365a6bd39.png)

</details>

([This code has "workarounds" for points 1, 2 and 3 included](https://gist.github.com/alvinhochun/9cd2f19d3b15c7dd611c38e0c65ec969#file-camera2-rs))

I think it would make sense for Kiss3d to provide a convenient method to draw text at a 3D point as a way to display data associated with the point, but it seems to me that it will take quite a bit of work to implement properly. But I'm also looking for some pointers on making my code work as expected.

---
\*1: An example is with camera `eye = Point3::new(0.0f32, -20.0, 10.0)` and `at = Point3::origin()` projecting the point `Point3::new(0.0, -25.0, 0.0)`.

**Comment by alvinhochun** [comment]
Update: I got it working in an acceptable manner. The code now looks like this:

```rust
fn draw_text(
    window: &mut Window,
    camera: &FirstPerson,
    text: &str,
    pos: &Point3<f32>,
    scale: f32,
    font: &std::rc::Rc<Font>,
    color: &Point3<f32>,
) {
    let pos_vector = pos - camera.eye();
    let dist = pos_vector.dot(&camera.eye_dir());
    if dist < 0.1 || dist > 20.0 {
        return;
    }
    let window_size = Vector2::new(window.size()[0] as f32, window.size()[1] as f32);
    let mut window_coord = camera.project(pos, &window_size);
    if window_coord.x.is_nan() || window_coord.y.is_nan() {
        return;
    }
    window_coord.y = window_size.y - window_coord.y;
    if window_coord.x >= window_size.x
        || window_coord.x < 0.0
        || window_coord.y >= window_size.y
        || window_coord.y < 0.0
    {
        return;
    }
    window.draw_text(text, &(window_coord * 2.0).into(), scale, font, color);
}
```

Of course this code in its current state is not suitable to be included in Kiss3d itself.

**Comment by douchuan** [comment]
> Update: I got it working in an acceptable manner. The code now looks like this:
> 
> ```rust
> fn draw_text(
>     window: &mut Window,
>     camera: &FirstPerson,
>     text: &str,
>     pos: &Point3<f32>,
>     scale: f32,
>     font: &std::rc::Rc<Font>,
>     color: &Point3<f32>,
> ) {
>     let pos_vector = pos - camera.eye();
>     let dist = pos_vector.dot(&camera.eye_dir());
>     if dist < 0.1 || dist > 20.0 {
>         return;
>     }
>     let window_size = Vector2::new(window.size()[0] as f32, window.size()[1] as f32);
>     let mut window_coord = camera.project(pos, &window_size);
>     if window_coord.x.is_nan() || window_coord.y.is_nan() {
>         return;
>     }
>     window_coord.y = window_size.y - window_coord.y;
>     if window_coord.x >= window_size.x
>         || window_coord.x < 0.0
>         || window_coord.y >= window_size.y
>         || window_coord.y < 0.0
>     {
>         return;
>     }
>     window.draw_text(text, &(window_coord * 2.0).into(), scale, font, color);
> }
> ```
> 
> Of course this code in its current state is not suitable to be included in Kiss3d itself.

cool, work for me

**Comment by caemanswartz** [comment]
I also wanted to do this in a project of mine and stumbled upon the same problem.  Your code isn't bad but I'm not quite sure you understand what you are doing (although the checks are nice). The project is definitely the right first step but its not all the translations needed. If you know about the rendering pipeline, you know that MVP calculation is actually not the last step.  What we need to do now is convert the 2D point of signed values into a 2D unsigned value that maps to an array from 0,0 to our screen dimensions.  My solution was to do the translation, which as the internet told me was the follow and it _seems_ to work well:
```
        let window_size = Vector2::new(window.size()[0] as f32, window.size()[1] as f32);
        let window_coordinate = camera.project(&position, &window_size);
        window.draw_text(
            &text,
            &Point2::new(
                // This here is how you translate from 2D world point to screen pixel
                2.0 * window_coordinate.x * window_size.x / window_size.x, // The X translation
                2.0 * (window_size.y - window_coordinate.y) * window_size.y / window_size.y // The Y translation
            ),
            size,
            &Font::default(),
            color
        );
```
Feel free to use those lines of code, it's just math so it should be public domain, if not, I Unlicense it.

**Comment by alvinhochun** [comment]
@caemanswartz I'm not seeing your point. In your code you multiply the coordinates by the window size and then divide the result by the same window size, which is almost effectively a no-op. The y-axis transformation you do is the same as what I was doing in my follow-up comment. Is there something that I missed?

**Comment by caemanswartz** [comment]
> which is almost effectively a no-op

Haha, I forgot I left this in, it is partly just an artifact from my lazy conversion of the equation at first but I left it since I added parallelization to slow down my debug simulation. I haven't taken complete control of the rendering loop yet, so it just runs as fast as it can. The compiler will optimize it away for release builds and makes it way too fast to watch some of it.

> Is there something that I missed?

If you already understood the conceptual point of the mapping, no? I was simply explaining the rational, or I guess what I am saying is that this is the best you could get (sans my useless multiply and divide)? Assuming of course that all values are real are numbers, the checks should be unneeded.  Like the only way you could get a NaN would be if the position or transformation matrix has a NaN, which, at least in my project, would cause the program to crash (assuming a NaN position would cause a crash) before I even attempted to draw the text, since I draw a sphere and point at the same location before text. I also believe the renderer handles canvas bounds checking, so there is no need to check if it is range. My 3D, Au scale, f64 based n-body simulator of our solar system _seems_ to work with out any of these checks. I could, of course, be wrong; I haven't done the math or even really looked at it in depth; as of now, my program is just one of those 'fire and forget' / 'watch the pretty colors' kind of things.

But I also just recently noticed some add overflow errors; I didn't minimize my window and it seem to happen both in front or behind, and focused or unfocused. Looking only at the failing function code (don't remember which one off the top of my head), I notice that it doesn't guard against the possibility of a trunc return being the maximum value and then it adds to it which could lead to an overflow but I don't know if this is the same problem as yours, since it only seems to happen after I run the program for over a half hour and I have no idea which of my 200+ bodies causes it, let alone where it is exactly after a who knows how many years of gravity simulation. For me, I really don't think there is a way to protect against this unless the function will check the value of the truncation before adding. The only other option I can think of is to figure out how it gets that value its truncating and make sure it never is passed a value that would cause an overflow but that sounds like too much digging to me, if it is even possible. In your case, I would try just not having any whole number coordinates and see if that resolves things as it should theoretically solve this problem since then trunc could never return the max value. Then again, it could be the tunc is just being done on a NaN. There is also [std::panic::catch_unwind](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html) which can prevent crashing if the panic doesn't abort the process and help diagnose your problem.
