### ISSUE TITLE
Error running the example on windows 10

### ISSUE THREAD

**Issue by dopic** [sebcrozet/kiss3d#96]
I tried to run the example on Windows 10, but I got the error: 

![image](https://user-images.githubusercontent.com/937765/30715073-7e73c318-9eeb-11e7-8623-a1c1873f16e0.png)

**Comment by AdamRzepka** [comment]
It's probably caused by missing freetype.dll. You can put it into working directory or somewhere in your PATH. However, I think it's just a workaround for poorly done freetype-sys binding. This issue is connected with https://github.com/PistonDevelopers/freetype-sys/issues/50. For kiss3d, the best solution would be to use servo/rust-freetype (which builds freetype.dll during cargo build) or, even better, redox-os/RustType instead of  PistonDevelopers/freetype-rs.

**Comment by dopic** [comment]
Thanks for the advice! Now it's working!
