### ISSUE TITLE
Text projection in 3D problem

### ISSUE THREAD

**Issue by twistezo** [sebcrozet/kiss3d#98]
1. Function `camera::Camera::project(...) ` doesn't reverse value of `y` axis.
2. Function `window::Window::draw_text(...)` from unknonw reason sees window size two times bigger than it is.

Below is example and workaround of these problems.
```
extern crate kiss3d;
extern crate nalgebra as na;

use std::path::Path;
use na::{Point2, Point3, Translation3, UnitQuaternion, Vector3};
use kiss3d::window::Window;
use kiss3d::camera::FirstPerson;
use kiss3d::light::Light;
use kiss3d::text::Font;
use kiss3d::camera::Camera;

fn main() {
    let mut window = Window::new_with_size("Test", 800, 600);
    window.set_background_color(0.2, 0.6, 0.3);
    window.set_light(Light::StickToCamera);

    let eye = Point3::new(5.0, 5.0, 5.0);
    let at = Point3::origin();
    let mut camera = FirstPerson::new(eye, at);

    let font = Font::new(&Path::new("examples/media/font/Inconsolata.otf"), 30);
    let height = window.height();

    let mut c = window.add_cube(1.0, 1.0, 1.0);
    c.append_translation(&Translation3::new(0.0, 0.0, 0.0));

    while !window.should_close() {
        let text_position_in_3d = &na::Point3::new(0.0, 1.0, 0.0);
        let text_position_in_2d = camera.project(&text_position_in_3d, &window.size());
        window.draw_text(
            "cube",
            &na::Point2::new(
                text_position_in_2d.data[0] * 2.0,
                (height - text_position_in_2d.data[1]) * 2.0,
            ),
            &font,
            &Point3::new(1.0, 1.0, 1.0),
        );
        window.render_with_camera(&mut camera);
    }
}
```

**Comment by yuvallanger** [comment]
The solution here is still wonky. The projection is still very weird.

**Comment by sebcrozet** [comment]
Sorry I did not see this issue earlier! To answer the questions:

1. The projection provided by `FirstPerson` (or other non-planar cameras) is designed to be used to render the 3D geometries, so reversing the `y` would not make sense. If you need the axis reversed, you may append a reflection to the projection.
2. The reason why `draw_text` sees the window size twice as big may be due to the hidpi factor of your display. You may want to take this into account: https://docs.rs/kiss3d/0.18.0/kiss3d/window/struct.Window.html#method.hidpi_factor
